services:
  db:
    image: postgres:16
    container_name: sim-clinic-laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sim_clinic_laravel
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sim_clinic_laravel"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: