/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CentralRouteRouteImport } from './routes/central/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TenantIndexRouteImport } from './routes/$tenant/index'
import { Route as TenantClinicRouteRouteImport } from './routes/$tenant/clinic/route'
import { Route as TenantLoginRouteImport } from './routes/$tenant/login'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as CentralIndexRouteImport } from './routes/central/index'
import { Route as CentralLoginRouteImport } from './routes/central/login'
import { Route as DemoDataTableRouteImport } from './routes/demo/data-table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as InvitationsTokenRouteImport } from './routes/invitations/$token'
import { Route as TenantClinicIndexRouteImport } from './routes/$tenant/clinic/index'
import { Route as TenantClinicPosRouteRouteImport } from './routes/$tenant/clinic/pos/route'
import { Route as TenantTreatmentSlugRouteImport } from './routes/$tenant/treatment/$slug'
import { Route as MarketingArtikelIndexRouteImport } from './routes/_marketing/artikel/index'
import { Route as MarketingCartIndexRouteImport } from './routes/_marketing/cart/index'
import { Route as MarketingLocationsIndexRouteImport } from './routes/_marketing/locations/index'
import { Route as MarketingOnlineBookingIndexRouteImport } from './routes/_marketing/online-booking/index'
import { Route as MarketingPromoIndexRouteImport } from './routes/_marketing/promo/index'
import { Route as MarketingStoreIndexRouteImport } from './routes/_marketing/store/index'
import { Route as MarketingTreatmentSlugRouteImport } from './routes/_marketing/treatment/$slug'
import { Route as MarketingTreatmentsIndexRouteImport } from './routes/_marketing/treatments/index'
import { Route as CentralTenantsIndexRouteImport } from './routes/central/tenants/index'
import { Route as CentralWahaIndexRouteImport } from './routes/central/waha/index'
import { Route as TenantClinicActivityLogsIndexRouteImport } from './routes/$tenant/clinic/activity-logs/index'
import { Route as TenantClinicBookingsIndexRouteImport } from './routes/$tenant/clinic/bookings/index'
import { Route as TenantClinicBroadcastsIndexRouteImport } from './routes/$tenant/clinic/broadcasts/index'
import { Route as TenantClinicBroadcastsIdRouteImport } from './routes/$tenant/clinic/broadcasts/$id'
import { Route as TenantClinicCategoriesIndexRouteImport } from './routes/$tenant/clinic/categories/index'
import { Route as TenantClinicChatbotSettingsRouteImport } from './routes/$tenant/clinic/chatbot/settings'
import { Route as TenantClinicCompanyProfileIndexRouteImport } from './routes/$tenant/clinic/company-profile/index'
import { Route as TenantClinicCompanyProfileSettingsRouteImport } from './routes/$tenant/clinic/company-profile/settings'
import { Route as TenantClinicExpensesIndexRouteImport } from './routes/$tenant/clinic/expenses/index'
import { Route as TenantClinicInventoryIndexRouteImport } from './routes/$tenant/clinic/inventory/index'
import { Route as TenantClinicMedicalRecordsIndexRouteImport } from './routes/$tenant/clinic/medical-records/index'
import { Route as TenantClinicMedicalRecordsRecordIdRouteImport } from './routes/$tenant/clinic/medical-records/$recordId'
import { Route as TenantClinicMedicalRecordsNewRouteImport } from './routes/$tenant/clinic/medical-records/new'
import { Route as TenantClinicPatientsIndexRouteImport } from './routes/$tenant/clinic/patients/index'
import { Route as TenantClinicPatientsNewRouteImport } from './routes/$tenant/clinic/patients/new'
import { Route as TenantClinicPosIndexRouteImport } from './routes/$tenant/clinic/pos/index'
import { Route as TenantClinicPreferencesIndexRouteImport } from './routes/$tenant/clinic/preferences/index'
import { Route as TenantClinicProductsIndexRouteImport } from './routes/$tenant/clinic/products/index'
import { Route as TenantClinicPromosIndexRouteImport } from './routes/$tenant/clinic/promos/index'
import { Route as TenantClinicReportsIndexRouteImport } from './routes/$tenant/clinic/reports/index'
import { Route as TenantClinicRolesIndexRouteImport } from './routes/$tenant/clinic/roles/index'
import { Route as TenantClinicServicesIndexRouteImport } from './routes/$tenant/clinic/services/index'
import { Route as TenantClinicSettingsIndexRouteImport } from './routes/$tenant/clinic/settings/index'
import { Route as TenantClinicStaffIndexRouteImport } from './routes/$tenant/clinic/staff/index'
import { Route as TenantClinicCompanyProfileEntityIndexRouteImport } from './routes/$tenant/clinic/company-profile/$entity/index'
import { Route as TenantClinicCompanyProfileEntityIdRouteImport } from './routes/$tenant/clinic/company-profile/$entity/$id'
import { Route as TenantClinicCompanyProfileEntityNewRouteImport } from './routes/$tenant/clinic/company-profile/$entity/new'
import { Route as TenantClinicPatientsIdEditRouteImport } from './routes/$tenant/clinic/patients/$id/edit'
import { Route as TenantClinicPatientsIdHistoryRouteImport } from './routes/$tenant/clinic/patients/$id/history'
import { Route as TenantClinicPatientsIdMedicalRecordsRouteImport } from './routes/$tenant/clinic/patients/$id/medical-records'
import { Route as TenantClinicPosInvoicesIdRouteImport } from './routes/$tenant/clinic/pos/invoices/$id'
import { Route as TenantClinicPosTransactionsIndexRouteImport } from './routes/$tenant/clinic/pos/transactions/index'
import { Route as TenantClinicPosTransactionsIdRouteImport } from './routes/$tenant/clinic/pos/transactions/$id'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRouteRoute = CentralRouteRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/$tenant/',
  path: '/$tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantClinicRouteRoute = TenantClinicRouteRouteImport.update({
  id: '/$tenant/clinic',
  path: '/$tenant/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/$tenant/login',
  path: '/$tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const CentralIndexRoute = CentralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralRouteRoute,
} as any)
const CentralLoginRoute = CentralLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CentralRouteRoute,
} as any)
const DemoDataTableRoute = DemoDataTableRouteImport.update({
  id: '/demo/data-table',
  path: '/demo/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantClinicIndexRoute = TenantClinicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicPosRouteRoute = TenantClinicPosRouteRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantTreatmentSlugRoute = TenantTreatmentSlugRouteImport.update({
  id: '/$tenant/treatment/$slug',
  path: '/$tenant/treatment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingArtikelIndexRoute = MarketingArtikelIndexRouteImport.update({
  id: '/artikel/',
  path: '/artikel/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingCartIndexRoute = MarketingCartIndexRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingLocationsIndexRoute = MarketingLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOnlineBookingIndexRoute =
  MarketingOnlineBookingIndexRouteImport.update({
    id: '/online-booking/',
    path: '/online-booking/',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingPromoIndexRoute = MarketingPromoIndexRouteImport.update({
  id: '/promo/',
  path: '/promo/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingStoreIndexRoute = MarketingStoreIndexRouteImport.update({
  id: '/store/',
  path: '/store/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTreatmentSlugRoute = MarketingTreatmentSlugRouteImport.update({
  id: '/treatment/$slug',
  path: '/treatment/$slug',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingTreatmentsIndexRoute =
  MarketingTreatmentsIndexRouteImport.update({
    id: '/treatments/',
    path: '/treatments/',
    getParentRoute: () => MarketingRoute,
  } as any)
const CentralTenantsIndexRoute = CentralTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => CentralRouteRoute,
} as any)
const CentralWahaIndexRoute = CentralWahaIndexRouteImport.update({
  id: '/waha/',
  path: '/waha/',
  getParentRoute: () => CentralRouteRoute,
} as any)
const TenantClinicActivityLogsIndexRoute =
  TenantClinicActivityLogsIndexRouteImport.update({
    id: '/activity-logs/',
    path: '/activity-logs/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicBookingsIndexRoute =
  TenantClinicBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicBroadcastsIndexRoute =
  TenantClinicBroadcastsIndexRouteImport.update({
    id: '/broadcasts/',
    path: '/broadcasts/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicBroadcastsIdRoute =
  TenantClinicBroadcastsIdRouteImport.update({
    id: '/broadcasts/$id',
    path: '/broadcasts/$id',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCategoriesIndexRoute =
  TenantClinicCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicChatbotSettingsRoute =
  TenantClinicChatbotSettingsRouteImport.update({
    id: '/chatbot/settings',
    path: '/chatbot/settings',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileIndexRoute =
  TenantClinicCompanyProfileIndexRouteImport.update({
    id: '/company-profile/',
    path: '/company-profile/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileSettingsRoute =
  TenantClinicCompanyProfileSettingsRouteImport.update({
    id: '/company-profile/settings',
    path: '/company-profile/settings',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicExpensesIndexRoute =
  TenantClinicExpensesIndexRouteImport.update({
    id: '/expenses/',
    path: '/expenses/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicInventoryIndexRoute =
  TenantClinicInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicMedicalRecordsIndexRoute =
  TenantClinicMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicMedicalRecordsRecordIdRoute =
  TenantClinicMedicalRecordsRecordIdRouteImport.update({
    id: '/medical-records/$recordId',
    path: '/medical-records/$recordId',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicMedicalRecordsNewRoute =
  TenantClinicMedicalRecordsNewRouteImport.update({
    id: '/medical-records/new',
    path: '/medical-records/new',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIndexRoute =
  TenantClinicPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsNewRoute = TenantClinicPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicPosIndexRoute = TenantClinicPosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantClinicPosRouteRoute,
} as any)
const TenantClinicPreferencesIndexRoute =
  TenantClinicPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicProductsIndexRoute =
  TenantClinicProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPromosIndexRoute = TenantClinicPromosIndexRouteImport.update({
  id: '/promos/',
  path: '/promos/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicReportsIndexRoute =
  TenantClinicReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicRolesIndexRoute = TenantClinicRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicServicesIndexRoute =
  TenantClinicServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicSettingsIndexRoute =
  TenantClinicSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicStaffIndexRoute = TenantClinicStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicCompanyProfileEntityIndexRoute =
  TenantClinicCompanyProfileEntityIndexRouteImport.update({
    id: '/company-profile/$entity/',
    path: '/company-profile/$entity/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileEntityIdRoute =
  TenantClinicCompanyProfileEntityIdRouteImport.update({
    id: '/company-profile/$entity/$id',
    path: '/company-profile/$entity/$id',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileEntityNewRoute =
  TenantClinicCompanyProfileEntityNewRouteImport.update({
    id: '/company-profile/$entity/new',
    path: '/company-profile/$entity/new',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIdEditRoute =
  TenantClinicPatientsIdEditRouteImport.update({
    id: '/patients/$id/edit',
    path: '/patients/$id/edit',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIdHistoryRoute =
  TenantClinicPatientsIdHistoryRouteImport.update({
    id: '/patients/$id/history',
    path: '/patients/$id/history',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIdMedicalRecordsRoute =
  TenantClinicPatientsIdMedicalRecordsRouteImport.update({
    id: '/patients/$id/medical-records',
    path: '/patients/$id/medical-records',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPosInvoicesIdRoute =
  TenantClinicPosInvoicesIdRouteImport.update({
    id: '/invoices/$id',
    path: '/invoices/$id',
    getParentRoute: () => TenantClinicPosRouteRoute,
  } as any)
const TenantClinicPosTransactionsIndexRoute =
  TenantClinicPosTransactionsIndexRouteImport.update({
    id: '/transactions/',
    path: '/transactions/',
    getParentRoute: () => TenantClinicPosRouteRoute,
  } as any)
const TenantClinicPosTransactionsIdRoute =
  TenantClinicPosTransactionsIdRouteImport.update({
    id: '/transactions/$id',
    path: '/transactions/$id',
    getParentRoute: () => TenantClinicPosRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/central': typeof CentralRouteRouteWithChildren
  '/': typeof MarketingIndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/$tenant/clinic': typeof TenantClinicRouteRouteWithChildren
  '/$tenant/login': typeof TenantLoginRoute
  '/central/login': typeof CentralLoginRoute
  '/demo/data-table': typeof DemoDataTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/$tenant/': typeof TenantIndexRoute
  '/central/': typeof CentralIndexRoute
  '/$tenant/clinic/pos': typeof TenantClinicPosRouteRouteWithChildren
  '/$tenant/treatment/$slug': typeof TenantTreatmentSlugRoute
  '/treatment/$slug': typeof MarketingTreatmentSlugRoute
  '/$tenant/clinic/': typeof TenantClinicIndexRoute
  '/artikel/': typeof MarketingArtikelIndexRoute
  '/cart/': typeof MarketingCartIndexRoute
  '/locations/': typeof MarketingLocationsIndexRoute
  '/online-booking/': typeof MarketingOnlineBookingIndexRoute
  '/promo/': typeof MarketingPromoIndexRoute
  '/store/': typeof MarketingStoreIndexRoute
  '/treatments/': typeof MarketingTreatmentsIndexRoute
  '/central/tenants/': typeof CentralTenantsIndexRoute
  '/central/waha/': typeof CentralWahaIndexRoute
  '/$tenant/clinic/broadcasts/$id': typeof TenantClinicBroadcastsIdRoute
  '/$tenant/clinic/chatbot/settings': typeof TenantClinicChatbotSettingsRoute
  '/$tenant/clinic/company-profile/settings': typeof TenantClinicCompanyProfileSettingsRoute
  '/$tenant/clinic/medical-records/$recordId': typeof TenantClinicMedicalRecordsRecordIdRoute
  '/$tenant/clinic/medical-records/new': typeof TenantClinicMedicalRecordsNewRoute
  '/$tenant/clinic/patients/new': typeof TenantClinicPatientsNewRoute
  '/$tenant/clinic/activity-logs/': typeof TenantClinicActivityLogsIndexRoute
  '/$tenant/clinic/bookings/': typeof TenantClinicBookingsIndexRoute
  '/$tenant/clinic/broadcasts/': typeof TenantClinicBroadcastsIndexRoute
  '/$tenant/clinic/categories/': typeof TenantClinicCategoriesIndexRoute
  '/$tenant/clinic/company-profile/': typeof TenantClinicCompanyProfileIndexRoute
  '/$tenant/clinic/expenses/': typeof TenantClinicExpensesIndexRoute
  '/$tenant/clinic/inventory/': typeof TenantClinicInventoryIndexRoute
  '/$tenant/clinic/medical-records/': typeof TenantClinicMedicalRecordsIndexRoute
  '/$tenant/clinic/patients/': typeof TenantClinicPatientsIndexRoute
  '/$tenant/clinic/pos/': typeof TenantClinicPosIndexRoute
  '/$tenant/clinic/preferences/': typeof TenantClinicPreferencesIndexRoute
  '/$tenant/clinic/products/': typeof TenantClinicProductsIndexRoute
  '/$tenant/clinic/promos/': typeof TenantClinicPromosIndexRoute
  '/$tenant/clinic/reports/': typeof TenantClinicReportsIndexRoute
  '/$tenant/clinic/roles/': typeof TenantClinicRolesIndexRoute
  '/$tenant/clinic/services/': typeof TenantClinicServicesIndexRoute
  '/$tenant/clinic/settings/': typeof TenantClinicSettingsIndexRoute
  '/$tenant/clinic/staff/': typeof TenantClinicStaffIndexRoute
  '/$tenant/clinic/company-profile/$entity/$id': typeof TenantClinicCompanyProfileEntityIdRoute
  '/$tenant/clinic/company-profile/$entity/new': typeof TenantClinicCompanyProfileEntityNewRoute
  '/$tenant/clinic/patients/$id/edit': typeof TenantClinicPatientsIdEditRoute
  '/$tenant/clinic/patients/$id/history': typeof TenantClinicPatientsIdHistoryRoute
  '/$tenant/clinic/patients/$id/medical-records': typeof TenantClinicPatientsIdMedicalRecordsRoute
  '/$tenant/clinic/pos/invoices/$id': typeof TenantClinicPosInvoicesIdRoute
  '/$tenant/clinic/pos/transactions/$id': typeof TenantClinicPosTransactionsIdRoute
  '/$tenant/clinic/company-profile/$entity/': typeof TenantClinicCompanyProfileEntityIndexRoute
  '/$tenant/clinic/pos/transactions/': typeof TenantClinicPosTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/central/login': typeof CentralLoginRoute
  '/demo/data-table': typeof DemoDataTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/$tenant': typeof TenantIndexRoute
  '/': typeof MarketingIndexRoute
  '/central': typeof CentralIndexRoute
  '/$tenant/treatment/$slug': typeof TenantTreatmentSlugRoute
  '/treatment/$slug': typeof MarketingTreatmentSlugRoute
  '/$tenant/clinic': typeof TenantClinicIndexRoute
  '/artikel': typeof MarketingArtikelIndexRoute
  '/cart': typeof MarketingCartIndexRoute
  '/locations': typeof MarketingLocationsIndexRoute
  '/online-booking': typeof MarketingOnlineBookingIndexRoute
  '/promo': typeof MarketingPromoIndexRoute
  '/store': typeof MarketingStoreIndexRoute
  '/treatments': typeof MarketingTreatmentsIndexRoute
  '/central/tenants': typeof CentralTenantsIndexRoute
  '/central/waha': typeof CentralWahaIndexRoute
  '/$tenant/clinic/broadcasts/$id': typeof TenantClinicBroadcastsIdRoute
  '/$tenant/clinic/chatbot/settings': typeof TenantClinicChatbotSettingsRoute
  '/$tenant/clinic/company-profile/settings': typeof TenantClinicCompanyProfileSettingsRoute
  '/$tenant/clinic/medical-records/$recordId': typeof TenantClinicMedicalRecordsRecordIdRoute
  '/$tenant/clinic/medical-records/new': typeof TenantClinicMedicalRecordsNewRoute
  '/$tenant/clinic/patients/new': typeof TenantClinicPatientsNewRoute
  '/$tenant/clinic/activity-logs': typeof TenantClinicActivityLogsIndexRoute
  '/$tenant/clinic/bookings': typeof TenantClinicBookingsIndexRoute
  '/$tenant/clinic/broadcasts': typeof TenantClinicBroadcastsIndexRoute
  '/$tenant/clinic/categories': typeof TenantClinicCategoriesIndexRoute
  '/$tenant/clinic/company-profile': typeof TenantClinicCompanyProfileIndexRoute
  '/$tenant/clinic/expenses': typeof TenantClinicExpensesIndexRoute
  '/$tenant/clinic/inventory': typeof TenantClinicInventoryIndexRoute
  '/$tenant/clinic/medical-records': typeof TenantClinicMedicalRecordsIndexRoute
  '/$tenant/clinic/patients': typeof TenantClinicPatientsIndexRoute
  '/$tenant/clinic/pos': typeof TenantClinicPosIndexRoute
  '/$tenant/clinic/preferences': typeof TenantClinicPreferencesIndexRoute
  '/$tenant/clinic/products': typeof TenantClinicProductsIndexRoute
  '/$tenant/clinic/promos': typeof TenantClinicPromosIndexRoute
  '/$tenant/clinic/reports': typeof TenantClinicReportsIndexRoute
  '/$tenant/clinic/roles': typeof TenantClinicRolesIndexRoute
  '/$tenant/clinic/services': typeof TenantClinicServicesIndexRoute
  '/$tenant/clinic/settings': typeof TenantClinicSettingsIndexRoute
  '/$tenant/clinic/staff': typeof TenantClinicStaffIndexRoute
  '/$tenant/clinic/company-profile/$entity/$id': typeof TenantClinicCompanyProfileEntityIdRoute
  '/$tenant/clinic/company-profile/$entity/new': typeof TenantClinicCompanyProfileEntityNewRoute
  '/$tenant/clinic/patients/$id/edit': typeof TenantClinicPatientsIdEditRoute
  '/$tenant/clinic/patients/$id/history': typeof TenantClinicPatientsIdHistoryRoute
  '/$tenant/clinic/patients/$id/medical-records': typeof TenantClinicPatientsIdMedicalRecordsRoute
  '/$tenant/clinic/pos/invoices/$id': typeof TenantClinicPosInvoicesIdRoute
  '/$tenant/clinic/pos/transactions/$id': typeof TenantClinicPosTransactionsIdRoute
  '/$tenant/clinic/company-profile/$entity': typeof TenantClinicCompanyProfileEntityIndexRoute
  '/$tenant/clinic/pos/transactions': typeof TenantClinicPosTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/central': typeof CentralRouteRouteWithChildren
  '/_marketing': typeof MarketingRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/$tenant/clinic': typeof TenantClinicRouteRouteWithChildren
  '/$tenant/login': typeof TenantLoginRoute
  '/central/login': typeof CentralLoginRoute
  '/demo/data-table': typeof DemoDataTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/$tenant/': typeof TenantIndexRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/central/': typeof CentralIndexRoute
  '/$tenant/clinic/pos': typeof TenantClinicPosRouteRouteWithChildren
  '/$tenant/treatment/$slug': typeof TenantTreatmentSlugRoute
  '/_marketing/treatment/$slug': typeof MarketingTreatmentSlugRoute
  '/$tenant/clinic/': typeof TenantClinicIndexRoute
  '/_marketing/artikel/': typeof MarketingArtikelIndexRoute
  '/_marketing/cart/': typeof MarketingCartIndexRoute
  '/_marketing/locations/': typeof MarketingLocationsIndexRoute
  '/_marketing/online-booking/': typeof MarketingOnlineBookingIndexRoute
  '/_marketing/promo/': typeof MarketingPromoIndexRoute
  '/_marketing/store/': typeof MarketingStoreIndexRoute
  '/_marketing/treatments/': typeof MarketingTreatmentsIndexRoute
  '/central/tenants/': typeof CentralTenantsIndexRoute
  '/central/waha/': typeof CentralWahaIndexRoute
  '/$tenant/clinic/broadcasts/$id': typeof TenantClinicBroadcastsIdRoute
  '/$tenant/clinic/chatbot/settings': typeof TenantClinicChatbotSettingsRoute
  '/$tenant/clinic/company-profile/settings': typeof TenantClinicCompanyProfileSettingsRoute
  '/$tenant/clinic/medical-records/$recordId': typeof TenantClinicMedicalRecordsRecordIdRoute
  '/$tenant/clinic/medical-records/new': typeof TenantClinicMedicalRecordsNewRoute
  '/$tenant/clinic/patients/new': typeof TenantClinicPatientsNewRoute
  '/$tenant/clinic/activity-logs/': typeof TenantClinicActivityLogsIndexRoute
  '/$tenant/clinic/bookings/': typeof TenantClinicBookingsIndexRoute
  '/$tenant/clinic/broadcasts/': typeof TenantClinicBroadcastsIndexRoute
  '/$tenant/clinic/categories/': typeof TenantClinicCategoriesIndexRoute
  '/$tenant/clinic/company-profile/': typeof TenantClinicCompanyProfileIndexRoute
  '/$tenant/clinic/expenses/': typeof TenantClinicExpensesIndexRoute
  '/$tenant/clinic/inventory/': typeof TenantClinicInventoryIndexRoute
  '/$tenant/clinic/medical-records/': typeof TenantClinicMedicalRecordsIndexRoute
  '/$tenant/clinic/patients/': typeof TenantClinicPatientsIndexRoute
  '/$tenant/clinic/pos/': typeof TenantClinicPosIndexRoute
  '/$tenant/clinic/preferences/': typeof TenantClinicPreferencesIndexRoute
  '/$tenant/clinic/products/': typeof TenantClinicProductsIndexRoute
  '/$tenant/clinic/promos/': typeof TenantClinicPromosIndexRoute
  '/$tenant/clinic/reports/': typeof TenantClinicReportsIndexRoute
  '/$tenant/clinic/roles/': typeof TenantClinicRolesIndexRoute
  '/$tenant/clinic/services/': typeof TenantClinicServicesIndexRoute
  '/$tenant/clinic/settings/': typeof TenantClinicSettingsIndexRoute
  '/$tenant/clinic/staff/': typeof TenantClinicStaffIndexRoute
  '/$tenant/clinic/company-profile/$entity/$id': typeof TenantClinicCompanyProfileEntityIdRoute
  '/$tenant/clinic/company-profile/$entity/new': typeof TenantClinicCompanyProfileEntityNewRoute
  '/$tenant/clinic/patients/$id/edit': typeof TenantClinicPatientsIdEditRoute
  '/$tenant/clinic/patients/$id/history': typeof TenantClinicPatientsIdHistoryRoute
  '/$tenant/clinic/patients/$id/medical-records': typeof TenantClinicPatientsIdMedicalRecordsRoute
  '/$tenant/clinic/pos/invoices/$id': typeof TenantClinicPosInvoicesIdRoute
  '/$tenant/clinic/pos/transactions/$id': typeof TenantClinicPosTransactionsIdRoute
  '/$tenant/clinic/company-profile/$entity/': typeof TenantClinicCompanyProfileEntityIndexRoute
  '/$tenant/clinic/pos/transactions/': typeof TenantClinicPosTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/central'
    | '/'
    | '/about'
    | '/register'
    | '/$tenant/clinic'
    | '/$tenant/login'
    | '/central/login'
    | '/demo/data-table'
    | '/demo/tanstack-query'
    | '/invitations/$token'
    | '/$tenant/'
    | '/central/'
    | '/$tenant/clinic/pos'
    | '/$tenant/treatment/$slug'
    | '/treatment/$slug'
    | '/$tenant/clinic/'
    | '/artikel/'
    | '/cart/'
    | '/locations/'
    | '/online-booking/'
    | '/promo/'
    | '/store/'
    | '/treatments/'
    | '/central/tenants/'
    | '/central/waha/'
    | '/$tenant/clinic/broadcasts/$id'
    | '/$tenant/clinic/chatbot/settings'
    | '/$tenant/clinic/company-profile/settings'
    | '/$tenant/clinic/medical-records/$recordId'
    | '/$tenant/clinic/medical-records/new'
    | '/$tenant/clinic/patients/new'
    | '/$tenant/clinic/activity-logs/'
    | '/$tenant/clinic/bookings/'
    | '/$tenant/clinic/broadcasts/'
    | '/$tenant/clinic/categories/'
    | '/$tenant/clinic/company-profile/'
    | '/$tenant/clinic/expenses/'
    | '/$tenant/clinic/inventory/'
    | '/$tenant/clinic/medical-records/'
    | '/$tenant/clinic/patients/'
    | '/$tenant/clinic/pos/'
    | '/$tenant/clinic/preferences/'
    | '/$tenant/clinic/products/'
    | '/$tenant/clinic/promos/'
    | '/$tenant/clinic/reports/'
    | '/$tenant/clinic/roles/'
    | '/$tenant/clinic/services/'
    | '/$tenant/clinic/settings/'
    | '/$tenant/clinic/staff/'
    | '/$tenant/clinic/company-profile/$entity/$id'
    | '/$tenant/clinic/company-profile/$entity/new'
    | '/$tenant/clinic/patients/$id/edit'
    | '/$tenant/clinic/patients/$id/history'
    | '/$tenant/clinic/patients/$id/medical-records'
    | '/$tenant/clinic/pos/invoices/$id'
    | '/$tenant/clinic/pos/transactions/$id'
    | '/$tenant/clinic/company-profile/$entity/'
    | '/$tenant/clinic/pos/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/register'
    | '/$tenant/login'
    | '/central/login'
    | '/demo/data-table'
    | '/demo/tanstack-query'
    | '/invitations/$token'
    | '/$tenant'
    | '/'
    | '/central'
    | '/$tenant/treatment/$slug'
    | '/treatment/$slug'
    | '/$tenant/clinic'
    | '/artikel'
    | '/cart'
    | '/locations'
    | '/online-booking'
    | '/promo'
    | '/store'
    | '/treatments'
    | '/central/tenants'
    | '/central/waha'
    | '/$tenant/clinic/broadcasts/$id'
    | '/$tenant/clinic/chatbot/settings'
    | '/$tenant/clinic/company-profile/settings'
    | '/$tenant/clinic/medical-records/$recordId'
    | '/$tenant/clinic/medical-records/new'
    | '/$tenant/clinic/patients/new'
    | '/$tenant/clinic/activity-logs'
    | '/$tenant/clinic/bookings'
    | '/$tenant/clinic/broadcasts'
    | '/$tenant/clinic/categories'
    | '/$tenant/clinic/company-profile'
    | '/$tenant/clinic/expenses'
    | '/$tenant/clinic/inventory'
    | '/$tenant/clinic/medical-records'
    | '/$tenant/clinic/patients'
    | '/$tenant/clinic/pos'
    | '/$tenant/clinic/preferences'
    | '/$tenant/clinic/products'
    | '/$tenant/clinic/promos'
    | '/$tenant/clinic/reports'
    | '/$tenant/clinic/roles'
    | '/$tenant/clinic/services'
    | '/$tenant/clinic/settings'
    | '/$tenant/clinic/staff'
    | '/$tenant/clinic/company-profile/$entity/$id'
    | '/$tenant/clinic/company-profile/$entity/new'
    | '/$tenant/clinic/patients/$id/edit'
    | '/$tenant/clinic/patients/$id/history'
    | '/$tenant/clinic/patients/$id/medical-records'
    | '/$tenant/clinic/pos/invoices/$id'
    | '/$tenant/clinic/pos/transactions/$id'
    | '/$tenant/clinic/company-profile/$entity'
    | '/$tenant/clinic/pos/transactions'
  id:
    | '__root__'
    | '/central'
    | '/_marketing'
    | '/about'
    | '/register'
    | '/$tenant/clinic'
    | '/$tenant/login'
    | '/central/login'
    | '/demo/data-table'
    | '/demo/tanstack-query'
    | '/invitations/$token'
    | '/$tenant/'
    | '/_marketing/'
    | '/central/'
    | '/$tenant/clinic/pos'
    | '/$tenant/treatment/$slug'
    | '/_marketing/treatment/$slug'
    | '/$tenant/clinic/'
    | '/_marketing/artikel/'
    | '/_marketing/cart/'
    | '/_marketing/locations/'
    | '/_marketing/online-booking/'
    | '/_marketing/promo/'
    | '/_marketing/store/'
    | '/_marketing/treatments/'
    | '/central/tenants/'
    | '/central/waha/'
    | '/$tenant/clinic/broadcasts/$id'
    | '/$tenant/clinic/chatbot/settings'
    | '/$tenant/clinic/company-profile/settings'
    | '/$tenant/clinic/medical-records/$recordId'
    | '/$tenant/clinic/medical-records/new'
    | '/$tenant/clinic/patients/new'
    | '/$tenant/clinic/activity-logs/'
    | '/$tenant/clinic/bookings/'
    | '/$tenant/clinic/broadcasts/'
    | '/$tenant/clinic/categories/'
    | '/$tenant/clinic/company-profile/'
    | '/$tenant/clinic/expenses/'
    | '/$tenant/clinic/inventory/'
    | '/$tenant/clinic/medical-records/'
    | '/$tenant/clinic/patients/'
    | '/$tenant/clinic/pos/'
    | '/$tenant/clinic/preferences/'
    | '/$tenant/clinic/products/'
    | '/$tenant/clinic/promos/'
    | '/$tenant/clinic/reports/'
    | '/$tenant/clinic/roles/'
    | '/$tenant/clinic/services/'
    | '/$tenant/clinic/settings/'
    | '/$tenant/clinic/staff/'
    | '/$tenant/clinic/company-profile/$entity/$id'
    | '/$tenant/clinic/company-profile/$entity/new'
    | '/$tenant/clinic/patients/$id/edit'
    | '/$tenant/clinic/patients/$id/history'
    | '/$tenant/clinic/patients/$id/medical-records'
    | '/$tenant/clinic/pos/invoices/$id'
    | '/$tenant/clinic/pos/transactions/$id'
    | '/$tenant/clinic/company-profile/$entity/'
    | '/$tenant/clinic/pos/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CentralRouteRoute: typeof CentralRouteRouteWithChildren
  MarketingRoute: typeof MarketingRouteWithChildren
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRoute
  TenantClinicRouteRoute: typeof TenantClinicRouteRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
  DemoDataTableRoute: typeof DemoDataTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantTreatmentSlugRoute: typeof TenantTreatmentSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/$tenant'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/clinic': {
      id: '/$tenant/clinic'
      path: '/$tenant/clinic'
      fullPath: '/$tenant/clinic'
      preLoaderRoute: typeof TenantClinicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/login': {
      id: '/$tenant/login'
      path: '/$tenant/login'
      fullPath: '/$tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/central/': {
      id: '/central/'
      path: '/'
      fullPath: '/central/'
      preLoaderRoute: typeof CentralIndexRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/central/login': {
      id: '/central/login'
      path: '/login'
      fullPath: '/central/login'
      preLoaderRoute: typeof CentralLoginRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/demo/data-table': {
      id: '/demo/data-table'
      path: '/demo/data-table'
      fullPath: '/demo/data-table'
      preLoaderRoute: typeof DemoDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/clinic/': {
      id: '/$tenant/clinic/'
      path: '/'
      fullPath: '/$tenant/clinic/'
      preLoaderRoute: typeof TenantClinicIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos': {
      id: '/$tenant/clinic/pos'
      path: '/pos'
      fullPath: '/$tenant/clinic/pos'
      preLoaderRoute: typeof TenantClinicPosRouteRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/treatment/$slug': {
      id: '/$tenant/treatment/$slug'
      path: '/$tenant/treatment/$slug'
      fullPath: '/$tenant/treatment/$slug'
      preLoaderRoute: typeof TenantTreatmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/artikel/': {
      id: '/_marketing/artikel/'
      path: '/artikel'
      fullPath: '/artikel/'
      preLoaderRoute: typeof MarketingArtikelIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/cart/': {
      id: '/_marketing/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof MarketingCartIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/locations/': {
      id: '/_marketing/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof MarketingLocationsIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/online-booking/': {
      id: '/_marketing/online-booking/'
      path: '/online-booking'
      fullPath: '/online-booking/'
      preLoaderRoute: typeof MarketingOnlineBookingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/promo/': {
      id: '/_marketing/promo/'
      path: '/promo'
      fullPath: '/promo/'
      preLoaderRoute: typeof MarketingPromoIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/store/': {
      id: '/_marketing/store/'
      path: '/store'
      fullPath: '/store/'
      preLoaderRoute: typeof MarketingStoreIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/treatment/$slug': {
      id: '/_marketing/treatment/$slug'
      path: '/treatment/$slug'
      fullPath: '/treatment/$slug'
      preLoaderRoute: typeof MarketingTreatmentSlugRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/treatments/': {
      id: '/_marketing/treatments/'
      path: '/treatments'
      fullPath: '/treatments/'
      preLoaderRoute: typeof MarketingTreatmentsIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/central/tenants/': {
      id: '/central/tenants/'
      path: '/tenants'
      fullPath: '/central/tenants/'
      preLoaderRoute: typeof CentralTenantsIndexRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/central/waha/': {
      id: '/central/waha/'
      path: '/waha'
      fullPath: '/central/waha/'
      preLoaderRoute: typeof CentralWahaIndexRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/$tenant/clinic/activity-logs/': {
      id: '/$tenant/clinic/activity-logs/'
      path: '/activity-logs'
      fullPath: '/$tenant/clinic/activity-logs/'
      preLoaderRoute: typeof TenantClinicActivityLogsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/bookings/': {
      id: '/$tenant/clinic/bookings/'
      path: '/bookings'
      fullPath: '/$tenant/clinic/bookings/'
      preLoaderRoute: typeof TenantClinicBookingsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/broadcasts/': {
      id: '/$tenant/clinic/broadcasts/'
      path: '/broadcasts'
      fullPath: '/$tenant/clinic/broadcasts/'
      preLoaderRoute: typeof TenantClinicBroadcastsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/broadcasts/$id': {
      id: '/$tenant/clinic/broadcasts/$id'
      path: '/broadcasts/$id'
      fullPath: '/$tenant/clinic/broadcasts/$id'
      preLoaderRoute: typeof TenantClinicBroadcastsIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/categories/': {
      id: '/$tenant/clinic/categories/'
      path: '/categories'
      fullPath: '/$tenant/clinic/categories/'
      preLoaderRoute: typeof TenantClinicCategoriesIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/chatbot/settings': {
      id: '/$tenant/clinic/chatbot/settings'
      path: '/chatbot/settings'
      fullPath: '/$tenant/clinic/chatbot/settings'
      preLoaderRoute: typeof TenantClinicChatbotSettingsRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/': {
      id: '/$tenant/clinic/company-profile/'
      path: '/company-profile'
      fullPath: '/$tenant/clinic/company-profile/'
      preLoaderRoute: typeof TenantClinicCompanyProfileIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/settings': {
      id: '/$tenant/clinic/company-profile/settings'
      path: '/company-profile/settings'
      fullPath: '/$tenant/clinic/company-profile/settings'
      preLoaderRoute: typeof TenantClinicCompanyProfileSettingsRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/expenses/': {
      id: '/$tenant/clinic/expenses/'
      path: '/expenses'
      fullPath: '/$tenant/clinic/expenses/'
      preLoaderRoute: typeof TenantClinicExpensesIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/inventory/': {
      id: '/$tenant/clinic/inventory/'
      path: '/inventory'
      fullPath: '/$tenant/clinic/inventory/'
      preLoaderRoute: typeof TenantClinicInventoryIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/medical-records/': {
      id: '/$tenant/clinic/medical-records/'
      path: '/medical-records'
      fullPath: '/$tenant/clinic/medical-records/'
      preLoaderRoute: typeof TenantClinicMedicalRecordsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/medical-records/$recordId': {
      id: '/$tenant/clinic/medical-records/$recordId'
      path: '/medical-records/$recordId'
      fullPath: '/$tenant/clinic/medical-records/$recordId'
      preLoaderRoute: typeof TenantClinicMedicalRecordsRecordIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/medical-records/new': {
      id: '/$tenant/clinic/medical-records/new'
      path: '/medical-records/new'
      fullPath: '/$tenant/clinic/medical-records/new'
      preLoaderRoute: typeof TenantClinicMedicalRecordsNewRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/': {
      id: '/$tenant/clinic/patients/'
      path: '/patients'
      fullPath: '/$tenant/clinic/patients/'
      preLoaderRoute: typeof TenantClinicPatientsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/new': {
      id: '/$tenant/clinic/patients/new'
      path: '/patients/new'
      fullPath: '/$tenant/clinic/patients/new'
      preLoaderRoute: typeof TenantClinicPatientsNewRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos/': {
      id: '/$tenant/clinic/pos/'
      path: '/'
      fullPath: '/$tenant/clinic/pos/'
      preLoaderRoute: typeof TenantClinicPosIndexRouteImport
      parentRoute: typeof TenantClinicPosRouteRoute
    }
    '/$tenant/clinic/preferences/': {
      id: '/$tenant/clinic/preferences/'
      path: '/preferences'
      fullPath: '/$tenant/clinic/preferences/'
      preLoaderRoute: typeof TenantClinicPreferencesIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/products/': {
      id: '/$tenant/clinic/products/'
      path: '/products'
      fullPath: '/$tenant/clinic/products/'
      preLoaderRoute: typeof TenantClinicProductsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/promos/': {
      id: '/$tenant/clinic/promos/'
      path: '/promos'
      fullPath: '/$tenant/clinic/promos/'
      preLoaderRoute: typeof TenantClinicPromosIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/reports/': {
      id: '/$tenant/clinic/reports/'
      path: '/reports'
      fullPath: '/$tenant/clinic/reports/'
      preLoaderRoute: typeof TenantClinicReportsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/roles/': {
      id: '/$tenant/clinic/roles/'
      path: '/roles'
      fullPath: '/$tenant/clinic/roles/'
      preLoaderRoute: typeof TenantClinicRolesIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/services/': {
      id: '/$tenant/clinic/services/'
      path: '/services'
      fullPath: '/$tenant/clinic/services/'
      preLoaderRoute: typeof TenantClinicServicesIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/settings/': {
      id: '/$tenant/clinic/settings/'
      path: '/settings'
      fullPath: '/$tenant/clinic/settings/'
      preLoaderRoute: typeof TenantClinicSettingsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/staff/': {
      id: '/$tenant/clinic/staff/'
      path: '/staff'
      fullPath: '/$tenant/clinic/staff/'
      preLoaderRoute: typeof TenantClinicStaffIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/$entity/': {
      id: '/$tenant/clinic/company-profile/$entity/'
      path: '/company-profile/$entity'
      fullPath: '/$tenant/clinic/company-profile/$entity/'
      preLoaderRoute: typeof TenantClinicCompanyProfileEntityIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/$entity/$id': {
      id: '/$tenant/clinic/company-profile/$entity/$id'
      path: '/company-profile/$entity/$id'
      fullPath: '/$tenant/clinic/company-profile/$entity/$id'
      preLoaderRoute: typeof TenantClinicCompanyProfileEntityIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/$entity/new': {
      id: '/$tenant/clinic/company-profile/$entity/new'
      path: '/company-profile/$entity/new'
      fullPath: '/$tenant/clinic/company-profile/$entity/new'
      preLoaderRoute: typeof TenantClinicCompanyProfileEntityNewRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/$id/edit': {
      id: '/$tenant/clinic/patients/$id/edit'
      path: '/patients/$id/edit'
      fullPath: '/$tenant/clinic/patients/$id/edit'
      preLoaderRoute: typeof TenantClinicPatientsIdEditRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/$id/history': {
      id: '/$tenant/clinic/patients/$id/history'
      path: '/patients/$id/history'
      fullPath: '/$tenant/clinic/patients/$id/history'
      preLoaderRoute: typeof TenantClinicPatientsIdHistoryRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/$id/medical-records': {
      id: '/$tenant/clinic/patients/$id/medical-records'
      path: '/patients/$id/medical-records'
      fullPath: '/$tenant/clinic/patients/$id/medical-records'
      preLoaderRoute: typeof TenantClinicPatientsIdMedicalRecordsRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos/invoices/$id': {
      id: '/$tenant/clinic/pos/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/$tenant/clinic/pos/invoices/$id'
      preLoaderRoute: typeof TenantClinicPosInvoicesIdRouteImport
      parentRoute: typeof TenantClinicPosRouteRoute
    }
    '/$tenant/clinic/pos/transactions/': {
      id: '/$tenant/clinic/pos/transactions/'
      path: '/transactions'
      fullPath: '/$tenant/clinic/pos/transactions/'
      preLoaderRoute: typeof TenantClinicPosTransactionsIndexRouteImport
      parentRoute: typeof TenantClinicPosRouteRoute
    }
    '/$tenant/clinic/pos/transactions/$id': {
      id: '/$tenant/clinic/pos/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/$tenant/clinic/pos/transactions/$id'
      preLoaderRoute: typeof TenantClinicPosTransactionsIdRouteImport
      parentRoute: typeof TenantClinicPosRouteRoute
    }
  }
}

interface CentralRouteRouteChildren {
  CentralLoginRoute: typeof CentralLoginRoute
  CentralIndexRoute: typeof CentralIndexRoute
  CentralTenantsIndexRoute: typeof CentralTenantsIndexRoute
  CentralWahaIndexRoute: typeof CentralWahaIndexRoute
}

const CentralRouteRouteChildren: CentralRouteRouteChildren = {
  CentralLoginRoute: CentralLoginRoute,
  CentralIndexRoute: CentralIndexRoute,
  CentralTenantsIndexRoute: CentralTenantsIndexRoute,
  CentralWahaIndexRoute: CentralWahaIndexRoute,
}

const CentralRouteRouteWithChildren = CentralRouteRoute._addFileChildren(
  CentralRouteRouteChildren,
)

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingTreatmentSlugRoute: typeof MarketingTreatmentSlugRoute
  MarketingArtikelIndexRoute: typeof MarketingArtikelIndexRoute
  MarketingCartIndexRoute: typeof MarketingCartIndexRoute
  MarketingLocationsIndexRoute: typeof MarketingLocationsIndexRoute
  MarketingOnlineBookingIndexRoute: typeof MarketingOnlineBookingIndexRoute
  MarketingPromoIndexRoute: typeof MarketingPromoIndexRoute
  MarketingStoreIndexRoute: typeof MarketingStoreIndexRoute
  MarketingTreatmentsIndexRoute: typeof MarketingTreatmentsIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingTreatmentSlugRoute: MarketingTreatmentSlugRoute,
  MarketingArtikelIndexRoute: MarketingArtikelIndexRoute,
  MarketingCartIndexRoute: MarketingCartIndexRoute,
  MarketingLocationsIndexRoute: MarketingLocationsIndexRoute,
  MarketingOnlineBookingIndexRoute: MarketingOnlineBookingIndexRoute,
  MarketingPromoIndexRoute: MarketingPromoIndexRoute,
  MarketingStoreIndexRoute: MarketingStoreIndexRoute,
  MarketingTreatmentsIndexRoute: MarketingTreatmentsIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface TenantClinicPosRouteRouteChildren {
  TenantClinicPosIndexRoute: typeof TenantClinicPosIndexRoute
  TenantClinicPosInvoicesIdRoute: typeof TenantClinicPosInvoicesIdRoute
  TenantClinicPosTransactionsIdRoute: typeof TenantClinicPosTransactionsIdRoute
  TenantClinicPosTransactionsIndexRoute: typeof TenantClinicPosTransactionsIndexRoute
}

const TenantClinicPosRouteRouteChildren: TenantClinicPosRouteRouteChildren = {
  TenantClinicPosIndexRoute: TenantClinicPosIndexRoute,
  TenantClinicPosInvoicesIdRoute: TenantClinicPosInvoicesIdRoute,
  TenantClinicPosTransactionsIdRoute: TenantClinicPosTransactionsIdRoute,
  TenantClinicPosTransactionsIndexRoute: TenantClinicPosTransactionsIndexRoute,
}

const TenantClinicPosRouteRouteWithChildren =
  TenantClinicPosRouteRoute._addFileChildren(TenantClinicPosRouteRouteChildren)

interface TenantClinicRouteRouteChildren {
  TenantClinicPosRouteRoute: typeof TenantClinicPosRouteRouteWithChildren
  TenantClinicIndexRoute: typeof TenantClinicIndexRoute
  TenantClinicBroadcastsIdRoute: typeof TenantClinicBroadcastsIdRoute
  TenantClinicChatbotSettingsRoute: typeof TenantClinicChatbotSettingsRoute
  TenantClinicCompanyProfileSettingsRoute: typeof TenantClinicCompanyProfileSettingsRoute
  TenantClinicMedicalRecordsRecordIdRoute: typeof TenantClinicMedicalRecordsRecordIdRoute
  TenantClinicMedicalRecordsNewRoute: typeof TenantClinicMedicalRecordsNewRoute
  TenantClinicPatientsNewRoute: typeof TenantClinicPatientsNewRoute
  TenantClinicActivityLogsIndexRoute: typeof TenantClinicActivityLogsIndexRoute
  TenantClinicBookingsIndexRoute: typeof TenantClinicBookingsIndexRoute
  TenantClinicBroadcastsIndexRoute: typeof TenantClinicBroadcastsIndexRoute
  TenantClinicCategoriesIndexRoute: typeof TenantClinicCategoriesIndexRoute
  TenantClinicCompanyProfileIndexRoute: typeof TenantClinicCompanyProfileIndexRoute
  TenantClinicExpensesIndexRoute: typeof TenantClinicExpensesIndexRoute
  TenantClinicInventoryIndexRoute: typeof TenantClinicInventoryIndexRoute
  TenantClinicMedicalRecordsIndexRoute: typeof TenantClinicMedicalRecordsIndexRoute
  TenantClinicPatientsIndexRoute: typeof TenantClinicPatientsIndexRoute
  TenantClinicPreferencesIndexRoute: typeof TenantClinicPreferencesIndexRoute
  TenantClinicProductsIndexRoute: typeof TenantClinicProductsIndexRoute
  TenantClinicPromosIndexRoute: typeof TenantClinicPromosIndexRoute
  TenantClinicReportsIndexRoute: typeof TenantClinicReportsIndexRoute
  TenantClinicRolesIndexRoute: typeof TenantClinicRolesIndexRoute
  TenantClinicServicesIndexRoute: typeof TenantClinicServicesIndexRoute
  TenantClinicSettingsIndexRoute: typeof TenantClinicSettingsIndexRoute
  TenantClinicStaffIndexRoute: typeof TenantClinicStaffIndexRoute
  TenantClinicCompanyProfileEntityIdRoute: typeof TenantClinicCompanyProfileEntityIdRoute
  TenantClinicCompanyProfileEntityNewRoute: typeof TenantClinicCompanyProfileEntityNewRoute
  TenantClinicPatientsIdEditRoute: typeof TenantClinicPatientsIdEditRoute
  TenantClinicPatientsIdHistoryRoute: typeof TenantClinicPatientsIdHistoryRoute
  TenantClinicPatientsIdMedicalRecordsRoute: typeof TenantClinicPatientsIdMedicalRecordsRoute
  TenantClinicCompanyProfileEntityIndexRoute: typeof TenantClinicCompanyProfileEntityIndexRoute
}

const TenantClinicRouteRouteChildren: TenantClinicRouteRouteChildren = {
  TenantClinicPosRouteRoute: TenantClinicPosRouteRouteWithChildren,
  TenantClinicIndexRoute: TenantClinicIndexRoute,
  TenantClinicBroadcastsIdRoute: TenantClinicBroadcastsIdRoute,
  TenantClinicChatbotSettingsRoute: TenantClinicChatbotSettingsRoute,
  TenantClinicCompanyProfileSettingsRoute:
    TenantClinicCompanyProfileSettingsRoute,
  TenantClinicMedicalRecordsRecordIdRoute:
    TenantClinicMedicalRecordsRecordIdRoute,
  TenantClinicMedicalRecordsNewRoute: TenantClinicMedicalRecordsNewRoute,
  TenantClinicPatientsNewRoute: TenantClinicPatientsNewRoute,
  TenantClinicActivityLogsIndexRoute: TenantClinicActivityLogsIndexRoute,
  TenantClinicBookingsIndexRoute: TenantClinicBookingsIndexRoute,
  TenantClinicBroadcastsIndexRoute: TenantClinicBroadcastsIndexRoute,
  TenantClinicCategoriesIndexRoute: TenantClinicCategoriesIndexRoute,
  TenantClinicCompanyProfileIndexRoute: TenantClinicCompanyProfileIndexRoute,
  TenantClinicExpensesIndexRoute: TenantClinicExpensesIndexRoute,
  TenantClinicInventoryIndexRoute: TenantClinicInventoryIndexRoute,
  TenantClinicMedicalRecordsIndexRoute: TenantClinicMedicalRecordsIndexRoute,
  TenantClinicPatientsIndexRoute: TenantClinicPatientsIndexRoute,
  TenantClinicPreferencesIndexRoute: TenantClinicPreferencesIndexRoute,
  TenantClinicProductsIndexRoute: TenantClinicProductsIndexRoute,
  TenantClinicPromosIndexRoute: TenantClinicPromosIndexRoute,
  TenantClinicReportsIndexRoute: TenantClinicReportsIndexRoute,
  TenantClinicRolesIndexRoute: TenantClinicRolesIndexRoute,
  TenantClinicServicesIndexRoute: TenantClinicServicesIndexRoute,
  TenantClinicSettingsIndexRoute: TenantClinicSettingsIndexRoute,
  TenantClinicStaffIndexRoute: TenantClinicStaffIndexRoute,
  TenantClinicCompanyProfileEntityIdRoute:
    TenantClinicCompanyProfileEntityIdRoute,
  TenantClinicCompanyProfileEntityNewRoute:
    TenantClinicCompanyProfileEntityNewRoute,
  TenantClinicPatientsIdEditRoute: TenantClinicPatientsIdEditRoute,
  TenantClinicPatientsIdHistoryRoute: TenantClinicPatientsIdHistoryRoute,
  TenantClinicPatientsIdMedicalRecordsRoute:
    TenantClinicPatientsIdMedicalRecordsRoute,
  TenantClinicCompanyProfileEntityIndexRoute:
    TenantClinicCompanyProfileEntityIndexRoute,
}

const TenantClinicRouteRouteWithChildren =
  TenantClinicRouteRoute._addFileChildren(TenantClinicRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CentralRouteRoute: CentralRouteRouteWithChildren,
  MarketingRoute: MarketingRouteWithChildren,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRoute,
  TenantClinicRouteRoute: TenantClinicRouteRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
  DemoDataTableRoute: DemoDataTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantTreatmentSlugRoute: TenantTreatmentSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
