/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CentralRouteRouteImport } from './routes/central/route'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TenantIndexRouteImport } from './routes/$tenant/index'
import { Route as TenantClinicRouteRouteImport } from './routes/$tenant/clinic/route'
import { Route as TenantLoginRouteImport } from './routes/$tenant/login'
import { Route as CentralIndexRouteImport } from './routes/central/index'
import { Route as CentralLoginRouteImport } from './routes/central/login'
import { Route as DemoDataTableRouteImport } from './routes/demo/data-table'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as InvitationsTokenRouteImport } from './routes/invitations/$token'
import { Route as TenantClinicIndexRouteImport } from './routes/$tenant/clinic/index'
import { Route as TenantTreatmentSlugRouteImport } from './routes/$tenant/treatment/$slug'
import { Route as TenantUsersIndexRouteImport } from './routes/$tenant/users/index'
import { Route as CentralTenantsIndexRouteImport } from './routes/central/tenants/index'
import { Route as TenantClinicBookingsIndexRouteImport } from './routes/$tenant/clinic/bookings/index'
import { Route as TenantClinicCompanyProfileIndexRouteImport } from './routes/$tenant/clinic/company-profile/index'
import { Route as TenantClinicCompanyProfileSettingsRouteImport } from './routes/$tenant/clinic/company-profile/settings'
import { Route as TenantClinicInventoryIndexRouteImport } from './routes/$tenant/clinic/inventory/index'
import { Route as TenantClinicMedicalRecordsIndexRouteImport } from './routes/$tenant/clinic/medical-records/index'
import { Route as TenantClinicMedicalRecordsRecordIdRouteImport } from './routes/$tenant/clinic/medical-records/$recordId'
import { Route as TenantClinicMedicalRecordsNewRouteImport } from './routes/$tenant/clinic/medical-records/new'
import { Route as TenantClinicPatientsIndexRouteImport } from './routes/$tenant/clinic/patients/index'
import { Route as TenantClinicPatientsNewRouteImport } from './routes/$tenant/clinic/patients/new'
import { Route as TenantClinicPosIndexRouteImport } from './routes/$tenant/clinic/pos/index'
import { Route as TenantClinicProductsIndexRouteImport } from './routes/$tenant/clinic/products/index'
import { Route as TenantClinicReportsIndexRouteImport } from './routes/$tenant/clinic/reports/index'
import { Route as TenantClinicServicesIndexRouteImport } from './routes/$tenant/clinic/services/index'
import { Route as TenantClinicStaffIndexRouteImport } from './routes/$tenant/clinic/staff/index'
import { Route as TenantClinicCompanyProfileEntityIndexRouteImport } from './routes/$tenant/clinic/company-profile/$entity/index'
import { Route as TenantClinicCompanyProfileEntityIdRouteImport } from './routes/$tenant/clinic/company-profile/$entity/$id'
import { Route as TenantClinicCompanyProfileEntityNewRouteImport } from './routes/$tenant/clinic/company-profile/$entity/new'
import { Route as TenantClinicPatientsIdEditRouteImport } from './routes/$tenant/clinic/patients/$id/edit'
import { Route as TenantClinicPatientsIdHistoryRouteImport } from './routes/$tenant/clinic/patients/$id/history'
import { Route as TenantClinicPatientsIdMedicalRecordsRouteImport } from './routes/$tenant/clinic/patients/$id/medical-records'
import { Route as TenantClinicPosInvoicesIdRouteImport } from './routes/$tenant/clinic/pos/invoices/$id'
import { Route as TenantClinicPosTransactionsIndexRouteImport } from './routes/$tenant/clinic/pos/transactions/index'
import { Route as TenantClinicPosTransactionsIdRouteImport } from './routes/$tenant/clinic/pos/transactions/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralRouteRoute = CentralRouteRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/$tenant/',
  path: '/$tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantClinicRouteRoute = TenantClinicRouteRouteImport.update({
  id: '/$tenant/clinic',
  path: '/$tenant/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoginRoute = TenantLoginRouteImport.update({
  id: '/$tenant/login',
  path: '/$tenant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralIndexRoute = CentralIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CentralRouteRoute,
} as any)
const CentralLoginRoute = CentralLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CentralRouteRoute,
} as any)
const DemoDataTableRoute = DemoDataTableRouteImport.update({
  id: '/demo/data-table',
  path: '/demo/data-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsTokenRoute = InvitationsTokenRouteImport.update({
  id: '/invitations/$token',
  path: '/invitations/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantClinicIndexRoute = TenantClinicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantTreatmentSlugRoute = TenantTreatmentSlugRouteImport.update({
  id: '/$tenant/treatment/$slug',
  path: '/$tenant/treatment/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantUsersIndexRoute = TenantUsersIndexRouteImport.update({
  id: '/$tenant/users/',
  path: '/$tenant/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralTenantsIndexRoute = CentralTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => CentralRouteRoute,
} as any)
const TenantClinicBookingsIndexRoute =
  TenantClinicBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileIndexRoute =
  TenantClinicCompanyProfileIndexRouteImport.update({
    id: '/company-profile/',
    path: '/company-profile/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileSettingsRoute =
  TenantClinicCompanyProfileSettingsRouteImport.update({
    id: '/company-profile/settings',
    path: '/company-profile/settings',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicInventoryIndexRoute =
  TenantClinicInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicMedicalRecordsIndexRoute =
  TenantClinicMedicalRecordsIndexRouteImport.update({
    id: '/medical-records/',
    path: '/medical-records/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicMedicalRecordsRecordIdRoute =
  TenantClinicMedicalRecordsRecordIdRouteImport.update({
    id: '/medical-records/$recordId',
    path: '/medical-records/$recordId',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicMedicalRecordsNewRoute =
  TenantClinicMedicalRecordsNewRouteImport.update({
    id: '/medical-records/new',
    path: '/medical-records/new',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIndexRoute =
  TenantClinicPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsNewRoute = TenantClinicPatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicPosIndexRoute = TenantClinicPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicProductsIndexRoute =
  TenantClinicProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicReportsIndexRoute =
  TenantClinicReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicServicesIndexRoute =
  TenantClinicServicesIndexRouteImport.update({
    id: '/services/',
    path: '/services/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicStaffIndexRoute = TenantClinicStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => TenantClinicRouteRoute,
} as any)
const TenantClinicCompanyProfileEntityIndexRoute =
  TenantClinicCompanyProfileEntityIndexRouteImport.update({
    id: '/company-profile/$entity/',
    path: '/company-profile/$entity/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileEntityIdRoute =
  TenantClinicCompanyProfileEntityIdRouteImport.update({
    id: '/company-profile/$entity/$id',
    path: '/company-profile/$entity/$id',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicCompanyProfileEntityNewRoute =
  TenantClinicCompanyProfileEntityNewRouteImport.update({
    id: '/company-profile/$entity/new',
    path: '/company-profile/$entity/new',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIdEditRoute =
  TenantClinicPatientsIdEditRouteImport.update({
    id: '/patients/$id/edit',
    path: '/patients/$id/edit',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIdHistoryRoute =
  TenantClinicPatientsIdHistoryRouteImport.update({
    id: '/patients/$id/history',
    path: '/patients/$id/history',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPatientsIdMedicalRecordsRoute =
  TenantClinicPatientsIdMedicalRecordsRouteImport.update({
    id: '/patients/$id/medical-records',
    path: '/patients/$id/medical-records',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPosInvoicesIdRoute =
  TenantClinicPosInvoicesIdRouteImport.update({
    id: '/pos/invoices/$id',
    path: '/pos/invoices/$id',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPosTransactionsIndexRoute =
  TenantClinicPosTransactionsIndexRouteImport.update({
    id: '/pos/transactions/',
    path: '/pos/transactions/',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)
const TenantClinicPosTransactionsIdRoute =
  TenantClinicPosTransactionsIdRouteImport.update({
    id: '/pos/transactions/$id',
    path: '/pos/transactions/$id',
    getParentRoute: () => TenantClinicRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/central': typeof CentralRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/$tenant/clinic': typeof TenantClinicRouteRouteWithChildren
  '/$tenant/login': typeof TenantLoginRoute
  '/central/login': typeof CentralLoginRoute
  '/demo/data-table': typeof DemoDataTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/$tenant/': typeof TenantIndexRoute
  '/central/': typeof CentralIndexRoute
  '/$tenant/treatment/$slug': typeof TenantTreatmentSlugRoute
  '/$tenant/clinic/': typeof TenantClinicIndexRoute
  '/$tenant/users/': typeof TenantUsersIndexRoute
  '/central/tenants/': typeof CentralTenantsIndexRoute
  '/$tenant/clinic/company-profile/settings': typeof TenantClinicCompanyProfileSettingsRoute
  '/$tenant/clinic/medical-records/$recordId': typeof TenantClinicMedicalRecordsRecordIdRoute
  '/$tenant/clinic/medical-records/new': typeof TenantClinicMedicalRecordsNewRoute
  '/$tenant/clinic/patients/new': typeof TenantClinicPatientsNewRoute
  '/$tenant/clinic/bookings/': typeof TenantClinicBookingsIndexRoute
  '/$tenant/clinic/company-profile/': typeof TenantClinicCompanyProfileIndexRoute
  '/$tenant/clinic/inventory/': typeof TenantClinicInventoryIndexRoute
  '/$tenant/clinic/medical-records/': typeof TenantClinicMedicalRecordsIndexRoute
  '/$tenant/clinic/patients/': typeof TenantClinicPatientsIndexRoute
  '/$tenant/clinic/pos/': typeof TenantClinicPosIndexRoute
  '/$tenant/clinic/products/': typeof TenantClinicProductsIndexRoute
  '/$tenant/clinic/reports/': typeof TenantClinicReportsIndexRoute
  '/$tenant/clinic/services/': typeof TenantClinicServicesIndexRoute
  '/$tenant/clinic/staff/': typeof TenantClinicStaffIndexRoute
  '/$tenant/clinic/company-profile/$entity/$id': typeof TenantClinicCompanyProfileEntityIdRoute
  '/$tenant/clinic/company-profile/$entity/new': typeof TenantClinicCompanyProfileEntityNewRoute
  '/$tenant/clinic/patients/$id/edit': typeof TenantClinicPatientsIdEditRoute
  '/$tenant/clinic/patients/$id/history': typeof TenantClinicPatientsIdHistoryRoute
  '/$tenant/clinic/patients/$id/medical-records': typeof TenantClinicPatientsIdMedicalRecordsRoute
  '/$tenant/clinic/pos/invoices/$id': typeof TenantClinicPosInvoicesIdRoute
  '/$tenant/clinic/pos/transactions/$id': typeof TenantClinicPosTransactionsIdRoute
  '/$tenant/clinic/company-profile/$entity/': typeof TenantClinicCompanyProfileEntityIndexRoute
  '/$tenant/clinic/pos/transactions/': typeof TenantClinicPosTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/$tenant/login': typeof TenantLoginRoute
  '/central/login': typeof CentralLoginRoute
  '/demo/data-table': typeof DemoDataTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/$tenant': typeof TenantIndexRoute
  '/central': typeof CentralIndexRoute
  '/$tenant/treatment/$slug': typeof TenantTreatmentSlugRoute
  '/$tenant/clinic': typeof TenantClinicIndexRoute
  '/$tenant/users': typeof TenantUsersIndexRoute
  '/central/tenants': typeof CentralTenantsIndexRoute
  '/$tenant/clinic/company-profile/settings': typeof TenantClinicCompanyProfileSettingsRoute
  '/$tenant/clinic/medical-records/$recordId': typeof TenantClinicMedicalRecordsRecordIdRoute
  '/$tenant/clinic/medical-records/new': typeof TenantClinicMedicalRecordsNewRoute
  '/$tenant/clinic/patients/new': typeof TenantClinicPatientsNewRoute
  '/$tenant/clinic/bookings': typeof TenantClinicBookingsIndexRoute
  '/$tenant/clinic/company-profile': typeof TenantClinicCompanyProfileIndexRoute
  '/$tenant/clinic/inventory': typeof TenantClinicInventoryIndexRoute
  '/$tenant/clinic/medical-records': typeof TenantClinicMedicalRecordsIndexRoute
  '/$tenant/clinic/patients': typeof TenantClinicPatientsIndexRoute
  '/$tenant/clinic/pos': typeof TenantClinicPosIndexRoute
  '/$tenant/clinic/products': typeof TenantClinicProductsIndexRoute
  '/$tenant/clinic/reports': typeof TenantClinicReportsIndexRoute
  '/$tenant/clinic/services': typeof TenantClinicServicesIndexRoute
  '/$tenant/clinic/staff': typeof TenantClinicStaffIndexRoute
  '/$tenant/clinic/company-profile/$entity/$id': typeof TenantClinicCompanyProfileEntityIdRoute
  '/$tenant/clinic/company-profile/$entity/new': typeof TenantClinicCompanyProfileEntityNewRoute
  '/$tenant/clinic/patients/$id/edit': typeof TenantClinicPatientsIdEditRoute
  '/$tenant/clinic/patients/$id/history': typeof TenantClinicPatientsIdHistoryRoute
  '/$tenant/clinic/patients/$id/medical-records': typeof TenantClinicPatientsIdMedicalRecordsRoute
  '/$tenant/clinic/pos/invoices/$id': typeof TenantClinicPosInvoicesIdRoute
  '/$tenant/clinic/pos/transactions/$id': typeof TenantClinicPosTransactionsIdRoute
  '/$tenant/clinic/company-profile/$entity': typeof TenantClinicCompanyProfileEntityIndexRoute
  '/$tenant/clinic/pos/transactions': typeof TenantClinicPosTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/central': typeof CentralRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/register': typeof RegisterRoute
  '/$tenant/clinic': typeof TenantClinicRouteRouteWithChildren
  '/$tenant/login': typeof TenantLoginRoute
  '/central/login': typeof CentralLoginRoute
  '/demo/data-table': typeof DemoDataTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/invitations/$token': typeof InvitationsTokenRoute
  '/$tenant/': typeof TenantIndexRoute
  '/central/': typeof CentralIndexRoute
  '/$tenant/treatment/$slug': typeof TenantTreatmentSlugRoute
  '/$tenant/clinic/': typeof TenantClinicIndexRoute
  '/$tenant/users/': typeof TenantUsersIndexRoute
  '/central/tenants/': typeof CentralTenantsIndexRoute
  '/$tenant/clinic/company-profile/settings': typeof TenantClinicCompanyProfileSettingsRoute
  '/$tenant/clinic/medical-records/$recordId': typeof TenantClinicMedicalRecordsRecordIdRoute
  '/$tenant/clinic/medical-records/new': typeof TenantClinicMedicalRecordsNewRoute
  '/$tenant/clinic/patients/new': typeof TenantClinicPatientsNewRoute
  '/$tenant/clinic/bookings/': typeof TenantClinicBookingsIndexRoute
  '/$tenant/clinic/company-profile/': typeof TenantClinicCompanyProfileIndexRoute
  '/$tenant/clinic/inventory/': typeof TenantClinicInventoryIndexRoute
  '/$tenant/clinic/medical-records/': typeof TenantClinicMedicalRecordsIndexRoute
  '/$tenant/clinic/patients/': typeof TenantClinicPatientsIndexRoute
  '/$tenant/clinic/pos/': typeof TenantClinicPosIndexRoute
  '/$tenant/clinic/products/': typeof TenantClinicProductsIndexRoute
  '/$tenant/clinic/reports/': typeof TenantClinicReportsIndexRoute
  '/$tenant/clinic/services/': typeof TenantClinicServicesIndexRoute
  '/$tenant/clinic/staff/': typeof TenantClinicStaffIndexRoute
  '/$tenant/clinic/company-profile/$entity/$id': typeof TenantClinicCompanyProfileEntityIdRoute
  '/$tenant/clinic/company-profile/$entity/new': typeof TenantClinicCompanyProfileEntityNewRoute
  '/$tenant/clinic/patients/$id/edit': typeof TenantClinicPatientsIdEditRoute
  '/$tenant/clinic/patients/$id/history': typeof TenantClinicPatientsIdHistoryRoute
  '/$tenant/clinic/patients/$id/medical-records': typeof TenantClinicPatientsIdMedicalRecordsRoute
  '/$tenant/clinic/pos/invoices/$id': typeof TenantClinicPosInvoicesIdRoute
  '/$tenant/clinic/pos/transactions/$id': typeof TenantClinicPosTransactionsIdRoute
  '/$tenant/clinic/company-profile/$entity/': typeof TenantClinicCompanyProfileEntityIndexRoute
  '/$tenant/clinic/pos/transactions/': typeof TenantClinicPosTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/central'
    | '/about'
    | '/register'
    | '/$tenant/clinic'
    | '/$tenant/login'
    | '/central/login'
    | '/demo/data-table'
    | '/demo/tanstack-query'
    | '/invitations/$token'
    | '/$tenant/'
    | '/central/'
    | '/$tenant/treatment/$slug'
    | '/$tenant/clinic/'
    | '/$tenant/users/'
    | '/central/tenants/'
    | '/$tenant/clinic/company-profile/settings'
    | '/$tenant/clinic/medical-records/$recordId'
    | '/$tenant/clinic/medical-records/new'
    | '/$tenant/clinic/patients/new'
    | '/$tenant/clinic/bookings/'
    | '/$tenant/clinic/company-profile/'
    | '/$tenant/clinic/inventory/'
    | '/$tenant/clinic/medical-records/'
    | '/$tenant/clinic/patients/'
    | '/$tenant/clinic/pos/'
    | '/$tenant/clinic/products/'
    | '/$tenant/clinic/reports/'
    | '/$tenant/clinic/services/'
    | '/$tenant/clinic/staff/'
    | '/$tenant/clinic/company-profile/$entity/$id'
    | '/$tenant/clinic/company-profile/$entity/new'
    | '/$tenant/clinic/patients/$id/edit'
    | '/$tenant/clinic/patients/$id/history'
    | '/$tenant/clinic/patients/$id/medical-records'
    | '/$tenant/clinic/pos/invoices/$id'
    | '/$tenant/clinic/pos/transactions/$id'
    | '/$tenant/clinic/company-profile/$entity/'
    | '/$tenant/clinic/pos/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/register'
    | '/$tenant/login'
    | '/central/login'
    | '/demo/data-table'
    | '/demo/tanstack-query'
    | '/invitations/$token'
    | '/$tenant'
    | '/central'
    | '/$tenant/treatment/$slug'
    | '/$tenant/clinic'
    | '/$tenant/users'
    | '/central/tenants'
    | '/$tenant/clinic/company-profile/settings'
    | '/$tenant/clinic/medical-records/$recordId'
    | '/$tenant/clinic/medical-records/new'
    | '/$tenant/clinic/patients/new'
    | '/$tenant/clinic/bookings'
    | '/$tenant/clinic/company-profile'
    | '/$tenant/clinic/inventory'
    | '/$tenant/clinic/medical-records'
    | '/$tenant/clinic/patients'
    | '/$tenant/clinic/pos'
    | '/$tenant/clinic/products'
    | '/$tenant/clinic/reports'
    | '/$tenant/clinic/services'
    | '/$tenant/clinic/staff'
    | '/$tenant/clinic/company-profile/$entity/$id'
    | '/$tenant/clinic/company-profile/$entity/new'
    | '/$tenant/clinic/patients/$id/edit'
    | '/$tenant/clinic/patients/$id/history'
    | '/$tenant/clinic/patients/$id/medical-records'
    | '/$tenant/clinic/pos/invoices/$id'
    | '/$tenant/clinic/pos/transactions/$id'
    | '/$tenant/clinic/company-profile/$entity'
    | '/$tenant/clinic/pos/transactions'
  id:
    | '__root__'
    | '/'
    | '/central'
    | '/about'
    | '/register'
    | '/$tenant/clinic'
    | '/$tenant/login'
    | '/central/login'
    | '/demo/data-table'
    | '/demo/tanstack-query'
    | '/invitations/$token'
    | '/$tenant/'
    | '/central/'
    | '/$tenant/treatment/$slug'
    | '/$tenant/clinic/'
    | '/$tenant/users/'
    | '/central/tenants/'
    | '/$tenant/clinic/company-profile/settings'
    | '/$tenant/clinic/medical-records/$recordId'
    | '/$tenant/clinic/medical-records/new'
    | '/$tenant/clinic/patients/new'
    | '/$tenant/clinic/bookings/'
    | '/$tenant/clinic/company-profile/'
    | '/$tenant/clinic/inventory/'
    | '/$tenant/clinic/medical-records/'
    | '/$tenant/clinic/patients/'
    | '/$tenant/clinic/pos/'
    | '/$tenant/clinic/products/'
    | '/$tenant/clinic/reports/'
    | '/$tenant/clinic/services/'
    | '/$tenant/clinic/staff/'
    | '/$tenant/clinic/company-profile/$entity/$id'
    | '/$tenant/clinic/company-profile/$entity/new'
    | '/$tenant/clinic/patients/$id/edit'
    | '/$tenant/clinic/patients/$id/history'
    | '/$tenant/clinic/patients/$id/medical-records'
    | '/$tenant/clinic/pos/invoices/$id'
    | '/$tenant/clinic/pos/transactions/$id'
    | '/$tenant/clinic/company-profile/$entity/'
    | '/$tenant/clinic/pos/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CentralRouteRoute: typeof CentralRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  RegisterRoute: typeof RegisterRoute
  TenantClinicRouteRoute: typeof TenantClinicRouteRouteWithChildren
  TenantLoginRoute: typeof TenantLoginRoute
  DemoDataTableRoute: typeof DemoDataTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  InvitationsTokenRoute: typeof InvitationsTokenRoute
  TenantIndexRoute: typeof TenantIndexRoute
  TenantTreatmentSlugRoute: typeof TenantTreatmentSlugRoute
  TenantUsersIndexRoute: typeof TenantUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central': {
      id: '/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof CentralRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/': {
      id: '/$tenant/'
      path: '/$tenant'
      fullPath: '/$tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/clinic': {
      id: '/$tenant/clinic'
      path: '/$tenant/clinic'
      fullPath: '/$tenant/clinic'
      preLoaderRoute: typeof TenantClinicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/login': {
      id: '/$tenant/login'
      path: '/$tenant/login'
      fullPath: '/$tenant/login'
      preLoaderRoute: typeof TenantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central/': {
      id: '/central/'
      path: '/'
      fullPath: '/central/'
      preLoaderRoute: typeof CentralIndexRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/central/login': {
      id: '/central/login'
      path: '/login'
      fullPath: '/central/login'
      preLoaderRoute: typeof CentralLoginRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/demo/data-table': {
      id: '/demo/data-table'
      path: '/demo/data-table'
      fullPath: '/demo/data-table'
      preLoaderRoute: typeof DemoDataTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations/$token': {
      id: '/invitations/$token'
      path: '/invitations/$token'
      fullPath: '/invitations/$token'
      preLoaderRoute: typeof InvitationsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/clinic/': {
      id: '/$tenant/clinic/'
      path: '/'
      fullPath: '/$tenant/clinic/'
      preLoaderRoute: typeof TenantClinicIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/treatment/$slug': {
      id: '/$tenant/treatment/$slug'
      path: '/$tenant/treatment/$slug'
      fullPath: '/$tenant/treatment/$slug'
      preLoaderRoute: typeof TenantTreatmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenant/users/': {
      id: '/$tenant/users/'
      path: '/$tenant/users'
      fullPath: '/$tenant/users/'
      preLoaderRoute: typeof TenantUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central/tenants/': {
      id: '/central/tenants/'
      path: '/tenants'
      fullPath: '/central/tenants/'
      preLoaderRoute: typeof CentralTenantsIndexRouteImport
      parentRoute: typeof CentralRouteRoute
    }
    '/$tenant/clinic/bookings/': {
      id: '/$tenant/clinic/bookings/'
      path: '/bookings'
      fullPath: '/$tenant/clinic/bookings/'
      preLoaderRoute: typeof TenantClinicBookingsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/': {
      id: '/$tenant/clinic/company-profile/'
      path: '/company-profile'
      fullPath: '/$tenant/clinic/company-profile/'
      preLoaderRoute: typeof TenantClinicCompanyProfileIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/settings': {
      id: '/$tenant/clinic/company-profile/settings'
      path: '/company-profile/settings'
      fullPath: '/$tenant/clinic/company-profile/settings'
      preLoaderRoute: typeof TenantClinicCompanyProfileSettingsRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/inventory/': {
      id: '/$tenant/clinic/inventory/'
      path: '/inventory'
      fullPath: '/$tenant/clinic/inventory/'
      preLoaderRoute: typeof TenantClinicInventoryIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/medical-records/': {
      id: '/$tenant/clinic/medical-records/'
      path: '/medical-records'
      fullPath: '/$tenant/clinic/medical-records/'
      preLoaderRoute: typeof TenantClinicMedicalRecordsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/medical-records/$recordId': {
      id: '/$tenant/clinic/medical-records/$recordId'
      path: '/medical-records/$recordId'
      fullPath: '/$tenant/clinic/medical-records/$recordId'
      preLoaderRoute: typeof TenantClinicMedicalRecordsRecordIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/medical-records/new': {
      id: '/$tenant/clinic/medical-records/new'
      path: '/medical-records/new'
      fullPath: '/$tenant/clinic/medical-records/new'
      preLoaderRoute: typeof TenantClinicMedicalRecordsNewRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/': {
      id: '/$tenant/clinic/patients/'
      path: '/patients'
      fullPath: '/$tenant/clinic/patients/'
      preLoaderRoute: typeof TenantClinicPatientsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/new': {
      id: '/$tenant/clinic/patients/new'
      path: '/patients/new'
      fullPath: '/$tenant/clinic/patients/new'
      preLoaderRoute: typeof TenantClinicPatientsNewRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos/': {
      id: '/$tenant/clinic/pos/'
      path: '/pos'
      fullPath: '/$tenant/clinic/pos/'
      preLoaderRoute: typeof TenantClinicPosIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/products/': {
      id: '/$tenant/clinic/products/'
      path: '/products'
      fullPath: '/$tenant/clinic/products/'
      preLoaderRoute: typeof TenantClinicProductsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/reports/': {
      id: '/$tenant/clinic/reports/'
      path: '/reports'
      fullPath: '/$tenant/clinic/reports/'
      preLoaderRoute: typeof TenantClinicReportsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/services/': {
      id: '/$tenant/clinic/services/'
      path: '/services'
      fullPath: '/$tenant/clinic/services/'
      preLoaderRoute: typeof TenantClinicServicesIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/staff/': {
      id: '/$tenant/clinic/staff/'
      path: '/staff'
      fullPath: '/$tenant/clinic/staff/'
      preLoaderRoute: typeof TenantClinicStaffIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/$entity/': {
      id: '/$tenant/clinic/company-profile/$entity/'
      path: '/company-profile/$entity'
      fullPath: '/$tenant/clinic/company-profile/$entity/'
      preLoaderRoute: typeof TenantClinicCompanyProfileEntityIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/$entity/$id': {
      id: '/$tenant/clinic/company-profile/$entity/$id'
      path: '/company-profile/$entity/$id'
      fullPath: '/$tenant/clinic/company-profile/$entity/$id'
      preLoaderRoute: typeof TenantClinicCompanyProfileEntityIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/company-profile/$entity/new': {
      id: '/$tenant/clinic/company-profile/$entity/new'
      path: '/company-profile/$entity/new'
      fullPath: '/$tenant/clinic/company-profile/$entity/new'
      preLoaderRoute: typeof TenantClinicCompanyProfileEntityNewRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/$id/edit': {
      id: '/$tenant/clinic/patients/$id/edit'
      path: '/patients/$id/edit'
      fullPath: '/$tenant/clinic/patients/$id/edit'
      preLoaderRoute: typeof TenantClinicPatientsIdEditRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/$id/history': {
      id: '/$tenant/clinic/patients/$id/history'
      path: '/patients/$id/history'
      fullPath: '/$tenant/clinic/patients/$id/history'
      preLoaderRoute: typeof TenantClinicPatientsIdHistoryRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/patients/$id/medical-records': {
      id: '/$tenant/clinic/patients/$id/medical-records'
      path: '/patients/$id/medical-records'
      fullPath: '/$tenant/clinic/patients/$id/medical-records'
      preLoaderRoute: typeof TenantClinicPatientsIdMedicalRecordsRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos/invoices/$id': {
      id: '/$tenant/clinic/pos/invoices/$id'
      path: '/pos/invoices/$id'
      fullPath: '/$tenant/clinic/pos/invoices/$id'
      preLoaderRoute: typeof TenantClinicPosInvoicesIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos/transactions/': {
      id: '/$tenant/clinic/pos/transactions/'
      path: '/pos/transactions'
      fullPath: '/$tenant/clinic/pos/transactions/'
      preLoaderRoute: typeof TenantClinicPosTransactionsIndexRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
    '/$tenant/clinic/pos/transactions/$id': {
      id: '/$tenant/clinic/pos/transactions/$id'
      path: '/pos/transactions/$id'
      fullPath: '/$tenant/clinic/pos/transactions/$id'
      preLoaderRoute: typeof TenantClinicPosTransactionsIdRouteImport
      parentRoute: typeof TenantClinicRouteRoute
    }
  }
}

interface CentralRouteRouteChildren {
  CentralLoginRoute: typeof CentralLoginRoute
  CentralIndexRoute: typeof CentralIndexRoute
  CentralTenantsIndexRoute: typeof CentralTenantsIndexRoute
}

const CentralRouteRouteChildren: CentralRouteRouteChildren = {
  CentralLoginRoute: CentralLoginRoute,
  CentralIndexRoute: CentralIndexRoute,
  CentralTenantsIndexRoute: CentralTenantsIndexRoute,
}

const CentralRouteRouteWithChildren = CentralRouteRoute._addFileChildren(
  CentralRouteRouteChildren,
)

interface TenantClinicRouteRouteChildren {
  TenantClinicIndexRoute: typeof TenantClinicIndexRoute
  TenantClinicCompanyProfileSettingsRoute: typeof TenantClinicCompanyProfileSettingsRoute
  TenantClinicMedicalRecordsRecordIdRoute: typeof TenantClinicMedicalRecordsRecordIdRoute
  TenantClinicMedicalRecordsNewRoute: typeof TenantClinicMedicalRecordsNewRoute
  TenantClinicPatientsNewRoute: typeof TenantClinicPatientsNewRoute
  TenantClinicBookingsIndexRoute: typeof TenantClinicBookingsIndexRoute
  TenantClinicCompanyProfileIndexRoute: typeof TenantClinicCompanyProfileIndexRoute
  TenantClinicInventoryIndexRoute: typeof TenantClinicInventoryIndexRoute
  TenantClinicMedicalRecordsIndexRoute: typeof TenantClinicMedicalRecordsIndexRoute
  TenantClinicPatientsIndexRoute: typeof TenantClinicPatientsIndexRoute
  TenantClinicPosIndexRoute: typeof TenantClinicPosIndexRoute
  TenantClinicProductsIndexRoute: typeof TenantClinicProductsIndexRoute
  TenantClinicReportsIndexRoute: typeof TenantClinicReportsIndexRoute
  TenantClinicServicesIndexRoute: typeof TenantClinicServicesIndexRoute
  TenantClinicStaffIndexRoute: typeof TenantClinicStaffIndexRoute
  TenantClinicCompanyProfileEntityIdRoute: typeof TenantClinicCompanyProfileEntityIdRoute
  TenantClinicCompanyProfileEntityNewRoute: typeof TenantClinicCompanyProfileEntityNewRoute
  TenantClinicPatientsIdEditRoute: typeof TenantClinicPatientsIdEditRoute
  TenantClinicPatientsIdHistoryRoute: typeof TenantClinicPatientsIdHistoryRoute
  TenantClinicPatientsIdMedicalRecordsRoute: typeof TenantClinicPatientsIdMedicalRecordsRoute
  TenantClinicPosInvoicesIdRoute: typeof TenantClinicPosInvoicesIdRoute
  TenantClinicPosTransactionsIdRoute: typeof TenantClinicPosTransactionsIdRoute
  TenantClinicCompanyProfileEntityIndexRoute: typeof TenantClinicCompanyProfileEntityIndexRoute
  TenantClinicPosTransactionsIndexRoute: typeof TenantClinicPosTransactionsIndexRoute
}

const TenantClinicRouteRouteChildren: TenantClinicRouteRouteChildren = {
  TenantClinicIndexRoute: TenantClinicIndexRoute,
  TenantClinicCompanyProfileSettingsRoute:
    TenantClinicCompanyProfileSettingsRoute,
  TenantClinicMedicalRecordsRecordIdRoute:
    TenantClinicMedicalRecordsRecordIdRoute,
  TenantClinicMedicalRecordsNewRoute: TenantClinicMedicalRecordsNewRoute,
  TenantClinicPatientsNewRoute: TenantClinicPatientsNewRoute,
  TenantClinicBookingsIndexRoute: TenantClinicBookingsIndexRoute,
  TenantClinicCompanyProfileIndexRoute: TenantClinicCompanyProfileIndexRoute,
  TenantClinicInventoryIndexRoute: TenantClinicInventoryIndexRoute,
  TenantClinicMedicalRecordsIndexRoute: TenantClinicMedicalRecordsIndexRoute,
  TenantClinicPatientsIndexRoute: TenantClinicPatientsIndexRoute,
  TenantClinicPosIndexRoute: TenantClinicPosIndexRoute,
  TenantClinicProductsIndexRoute: TenantClinicProductsIndexRoute,
  TenantClinicReportsIndexRoute: TenantClinicReportsIndexRoute,
  TenantClinicServicesIndexRoute: TenantClinicServicesIndexRoute,
  TenantClinicStaffIndexRoute: TenantClinicStaffIndexRoute,
  TenantClinicCompanyProfileEntityIdRoute:
    TenantClinicCompanyProfileEntityIdRoute,
  TenantClinicCompanyProfileEntityNewRoute:
    TenantClinicCompanyProfileEntityNewRoute,
  TenantClinicPatientsIdEditRoute: TenantClinicPatientsIdEditRoute,
  TenantClinicPatientsIdHistoryRoute: TenantClinicPatientsIdHistoryRoute,
  TenantClinicPatientsIdMedicalRecordsRoute:
    TenantClinicPatientsIdMedicalRecordsRoute,
  TenantClinicPosInvoicesIdRoute: TenantClinicPosInvoicesIdRoute,
  TenantClinicPosTransactionsIdRoute: TenantClinicPosTransactionsIdRoute,
  TenantClinicCompanyProfileEntityIndexRoute:
    TenantClinicCompanyProfileEntityIndexRoute,
  TenantClinicPosTransactionsIndexRoute: TenantClinicPosTransactionsIndexRoute,
}

const TenantClinicRouteRouteWithChildren =
  TenantClinicRouteRoute._addFileChildren(TenantClinicRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CentralRouteRoute: CentralRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  RegisterRoute: RegisterRoute,
  TenantClinicRouteRoute: TenantClinicRouteRouteWithChildren,
  TenantLoginRoute: TenantLoginRoute,
  DemoDataTableRoute: DemoDataTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  InvitationsTokenRoute: InvitationsTokenRoute,
  TenantIndexRoute: TenantIndexRoute,
  TenantTreatmentSlugRoute: TenantTreatmentSlugRoute,
  TenantUsersIndexRoute: TenantUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
